'use strict';
const KEY='heart-cards-v1';
const fonts={batang:'"Gowun Batang", Georgia, serif',hand:'"Gamja Flower", cursive',sans:'"Noto Sans KR", Arial, sans-serif'};
const themes={cream:{bg:'#fff9ee',fg:'#634637',mark:'❀'},pink:{bg:'#f7e0df',fg:'#804954',mark:'♡'},night:{bg:'#e7e5f0',fg:'#51496d',mark:'☾'},line:{bg:'#fffaf2',fg:'#614e3d',mark:'✧'}};
const $=s=>document.querySelector(s);
function toast(message){const el=$('.toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500);}
function readCards(){const raw=localStorage.getItem(KEY);if(!raw)return [];const data=JSON.parse(raw);if(!Array.isArray(data))throw Error('invalid');return data.filter(c=>c&&typeof c.to==='string'&&typeof c.message==='string'&&fonts[c.font]&&themes[c.theme]);}
function fitLetter(el){const p=el.querySelector('p');p.style.fontSize='';let size=parseFloat(getComputedStyle(p).fontSize);while(el.scrollHeight>el.clientHeight+1&&size>12){size-=.5;p.style.fontSize=size+'px';}}
const intro=$('#intro');if(intro){const remove=()=>intro.remove();$('.skip').addEventListener('click',remove);setTimeout(remove,7600);}
const editor=$('#editor');
if(editor){
 const state=()=>({to:$('#recipient').value.trim(),message:$('#message').value.trim(),font:editor.elements.font.value,theme:editor.elements.theme.value});
 function update(){const c=state(),el=$('#preview');el.className=`letter ${c.theme} ${c.font}`;$('#preview-to').textContent='To. '+(c.to||'소중한 너에게');$('#preview-message').textContent=c.message||'전하고 싶은 마음을 적어주세요.';el.querySelector('.ornament').textContent=themes[c.theme].mark;$('#count').textContent=$('#message').value.length;fitLetter(el);}
 editor.addEventListener('input',update);update();document.fonts.ready.then(update);window.addEventListener('resize',update);
 editor.addEventListener('submit',event=>{event.preventDefault();const c=state();if(!c.to||!c.message){toast('받는 사람과 메시지를 입력해주세요.');return;}try{const cards=readCards();cards.unshift({...c,id:Date.now().toString(36),date:new Date().toISOString()});localStorage.setItem(KEY,JSON.stringify(cards));location.href='board.html';}catch{toast('카드를 저장하지 못했어요. 브라우저 저장 공간과 설정을 확인해주세요.');}});
 $('#print').addEventListener('click',()=>window.print());
 $('#download').addEventListener('click',async()=>{const button=$('#download');button.disabled=true;try{await document.fonts.ready;const c=state(),t=themes[c.theme],canvas=document.createElement('canvas');canvas.width=900;canvas.height=1230;const ctx=canvas.getContext('2d');ctx.fillStyle=t.bg;ctx.fillRect(0,0,900,1230);if(c.theme==='line'){ctx.strokeStyle='#dfd6c7';for(let y=40;y<1230;y+=70){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(900,y);ctx.stroke();}}ctx.strokeStyle='#baa181';ctx.lineWidth=2;ctx.strokeRect(40,40,820,1150);ctx.lineWidth=1;ctx.strokeRect(52,52,796,1126);ctx.fillStyle=t.fg;ctx.textAlign='center';ctx.font=`70px ${fonts[c.font]}`;ctx.fillText(t.mark,450,155);
 const wrap=(text,size,width)=>{ctx.font=`${size}px ${fonts[c.font]}`;const lines=[];for(const paragraph of text.split('\n')){let line='';for(const char of paragraph){if(ctx.measureText(line+char).width>width&&line){lines.push(line);line=char;}else line+=char;}lines.push(line);}return lines;};
 const toLines=wrap('To. '+(c.to||'소중한 너에게'),48,720);let y=245;for(const line of toLines){ctx.fillText(line,450,y);y+=65;}ctx.font=`32px ${fonts[c.font]}`;ctx.fillText('· '+t.mark+' ·',450,y+25);const start=y+100;let size=44,lines=wrap(c.message||'전하고 싶은 마음을 적어주세요.',size,700);while(lines.length*size*1.8>1030-start&&size>24){size-=1;lines=wrap(c.message||'전하고 싶은 마음을 적어주세요.',size,700);}ctx.font=`${size}px ${fonts[c.font]}`;y=start+Math.max(0,(1030-start-lines.length*size*1.8)/2);for(const line of lines){ctx.fillText(line,450,y);y+=size*1.8;}ctx.font=`28px ${fonts[c.font]}`;ctx.fillText('마음을 담아',450,1130);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='마음을-담아-카드.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('카드 이미지를 저장했습니다.');}catch{toast('이미지를 저장하지 못했어요. 다시 시도해주세요.');}finally{button.disabled=false;}});
}
function renderBoard(){const board=$('#board');if(!board)return;board.replaceChildren();let cards;try{cards=readCards();}catch{$('#board-count').textContent='저장된 카드에 접근할 수 없어요.';const el=document.createElement('p');el.className='empty';el.textContent='브라우저 저장 설정을 확인해주세요.';board.append(el);return;}$('#board-count').textContent=`총 ${cards.length}개의 마음`;if(!cards.length){const el=document.createElement('p');el.className='empty';el.textContent='아직 남겨진 마음이 없어요. 첫 번째 카드를 작성해보세요.';board.append(el);return;}for(const c of cards){const item=document.createElement('div');item.className='board-item';const letter=document.createElement('article');letter.className=`letter ${c.theme} ${c.font}`;const ornament=document.createElement('div');ornament.className='ornament';ornament.textContent=themes[c.theme].mark;ornament.setAttribute('aria-hidden','true');const h=document.createElement('h2');h.textContent='To. '+c.to;const divider=document.createElement('div');divider.className='divider';divider.textContent='· '+themes[c.theme].mark+' ·';const p=document.createElement('p');p.textContent=c.message;const small=document.createElement('small');small.textContent='마음을 담아';letter.append(ornament,h,divider,p,small);const time=document.createElement('time');const date=new Date(c.date);if(!isNaN(date)){time.dateTime=c.date;time.textContent=date.toLocaleDateString('ko-KR');}item.append(letter,time);board.append(item);fitLetter(letter);}document.fonts.ready.then(()=>board.querySelectorAll('.letter').forEach(fitLetter));}
renderBoard();window.addEventListener('storage',renderBoard);window.addEventListener('resize',()=>document.querySelectorAll('.letter').forEach(fitLetter));
